# Generated by Django 3.1.1 on 2021-08-03 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20210803_0250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lable',
            new_name='Label',
        ),
    ]
