# Generated by Django 3.1.1 on 2021-08-03 09:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20210803_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.category'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
